# Generated by Django 5.1 on 2024-08-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name_plural': 'Настройка'},
        ),
    ]
