# Generated by Django 5.1 on 2024-08-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_setting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(choices=[('Сеть', 'Сеть'), ('Аналитик', 'Аналитик'), ('Развитие', 'Развитие')], max_length=155, verbose_name='Иконка')),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
